services:
  mongodb:
    image: mongo:latest
    container_name: togesong-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./database/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  backend:
    build: ./backend
    container_name: togesong-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      MONGODB_URI: mongodb://admin:admin@mongodb:27017/
      PORT: 5000
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: togesong-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    environment:
      VITE_CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      VITE_HOST: 0.0.0.0
      VITE_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    restart: always